### ISSUE TITLE
Update requests library please

### ISSUE THREAD

**Issue by slavaGanzin** [MarketSquare/robotframework-requests#405]
I do really enjoy fixing dependency issues in python, what a breeze.

But seriously after pip install robotframework-requests I get:

```
>>> from RequestsLibrary import RequestsLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/RequestsLibrary/__init__.py", line 1, in <module>
    from .DeprecatedKeywords import DeprecatedKeywords
  File "/usr/local/lib/python3.12/dist-packages/RequestsLibrary/DeprecatedKeywords.py", line 6, in <module>
    from RequestsLibrary import utils
  File "/usr/local/lib/python3.12/dist-packages/RequestsLibrary/utils.py", line 5, in <module>
    from requests.status_codes import codes
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'six.moves'
```

After:
```
pip uninstall urllib3
pip install urllib3
```

It works but shows warning:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```

After updating version of requests to latest it works without warnings.

```
python -v
Python 3.12.7
```

**Comment by lucagiove** [comment]
what version you have or robotframework-requests ? have you installed it with --pre option?

**Comment by slavaGanzin** [comment]
No. just plain pip install

```
pip freeze | grep robot

robotframework==7.1.1
robotframework-assertion-engine==3.0.3
robotframework-browser==18.9.1
robotframework-lint==1.1
robotframework-pythonlibcore==4.4.1
robotframework-requests==0.9.7

```
```
pip freeze | grep request
requests==2.32.3
requests-unixsocket==0.2.0
robotframework-requests==0.9.7
```

**Comment by lucagiove** [comment]
try with --pre option

**Comment by slavaGanzin** [comment]
I’m fine with my hack. If you are already have plans for fixing this, I’ll close the issue
