### ISSUE TITLE
RequestsLibrary always show in red in RIDE with an import error

### ISSUE THREAD

**Issue by jerry57** [MarketSquare/robotframework-requests#44]
Is there a reason that RequestsLibrary always shows in red with an import error?

Here is what appears in the RIDE log:

20141112 15:44:39.421 [INFO]: Started RIDE 1.3 using python version 2.7.6 with wx version 2.8.12.1 in darwin.

20141112 15:44:46.382 [WARN]: Importing test library "RequestsLibrary" failed

Traceback (most recent call last):
Importing test library 'RequestsLibrary' failed: ImportError: No module named http_client
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/RequestsLibrary/**init**.py", line 1, in <module>
    from keywords import RequestsKeywords
  File "/Library/Python/2.7/site-packages/RequestsLibrary/keywords.py", line 3, in <module>
    import vcr
  File "/Library/Python/2.7/site-packages/vcr/**init**.py", line 2, in <module>
    from .config import VCR
  File "/Library/Python/2.7/site-packages/vcr/config.py", line 6, in <module>
    from .cassette import Cassette
  File "/Library/Python/2.7/site-packages/vcr/cassette.py", line 12, in <module>
    from .patch import CassettePatcherBuilder
  File "/Library/Python/2.7/site-packages/vcr/patch.py", line 8, in <module>
    from .stubs import VCRHTTPConnection, VCRHTTPSConnection
  File "/Library/Python/2.7/site-packages/vcr/stubs/**init**.py", line 9, in <module>
    from six.moves.http_client import (
PYTHONPATH:
  /Users/jerry/Downloads/RobotFramework_SwingLibrary/v1.9.1/swinglibrary-1.9.1.jar
  /Library/Python/2.7/site-packages/robotide/lib/robot/libraries
  /Library/Python/2.7/site-packages/robotide/lib
  /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode
  /usr/local/bin
  /Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg
  /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
  /Library/Python/2.7/site-packages
  /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7
  .
  /Users/jerry/trunk/robotframework/de
  /Library/Python/2.7/site-packages/robotide/spec
  File "/Library/Python/2.7/site-packages/robotide/spec/librarymanager.py", line 76, in _fetch_keywords
    return get_import_result(path, library_args)
  File "/Library/Python/2.7/site-packages/robotide/spec/libraryfetcher.py", line 20, in get_import_result
    lib = TestLibrary(path, args)
  File "/Library/Python/2.7/site-packages/robotide/lib/robot/running/testlibraries.py", line 37, in TestLibrary
    libcode = importer.import_class_or_module(name)
  File "/Library/Python/2.7/site-packages/robotide/lib/robot/utils/importer.py", line 64, in import_class_or_module
    self._raise_import_failed(name, err)
  File "/Library/Python/2.7/site-packages/robotide/lib/robot/utils/importer.py", line 102, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by nagesh1hs** [comment]
Hi jerry57, 

  Your python library does not have the request library thats why your requests are not imported. 
  Try these commands it will work. 
1. pip uninstall robotframework-requests
2.pip install requests
3. pip install robotframework-requests
   Then run your robot frame work test cases it will work. 

Regards 
Nagesh
